# Generated by Django 3.0.8 on 2021-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportcars',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие диллера в России'),
        ),
    ]
